---
title: <center><h2> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GE461 Project 1</h2></center>
papersize: a4paper
author: <center> <b><br/>Gledis Zeneli 21701065</b> <br/> <br/> <b>Verdiyev Zulfugar 21701208</b> <br/> <br/>  <b>Muhammad Arham Khan 21701848</b></center>
always_allow_html: true
linkcolor: red
output: 
  bookdown::html_document2:
    theme: readable
    number_sections: false
    code_folding: "hide"
    toc: true
  bookdown::pdf_document2:
    number_sections: false
---

```{r setup, include=FALSE}
library(magrittr)
library(tidyverse)
library(car)
library(knitr)
library(kableExtra)
library(pander)
library(grid)
library(gridExtra)
library(ggplot2)
opts_chunk$set(echo = TRUE)

options(knitr.kable.NA =".") 
kable_format <- if (is_html_output()) "html" else "latex"
options(scipen = 999)
```

## Data
The data has been processed so that all the text fields have either been converted to numerical or to levels. The temperature data has been converted from <b>&#176;F</b> to <b>&#176;C</b>.

```{r collapse=TRUE}
library(RSQLite)
con <- dbConnect(SQLite(), "data/dodgers.sqlite") 

events <- tbl(con, "events") %>% 
  collect() %>% 
  mutate(month = factor(month, levels = c("APR","MAY","JUN","JUL","AUG","SEP","OCT")),
         # no need to change day
         # no need to change attend
         day_of_week = factor(day_of_week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")),
         opponent = factor(opponent, levels = c("Pirates", "Padres", "Braves", "Nationals", "Giants", "Rockies", "Snakes", "Cardinals", "Astros", "Brewers", "Angels", "White Sox", "Mets", "Reds", "Phillies", "Cubs", "Marlins")),
         temp = round((temp - 32)*5/9), # temp is converted from F to C.)
         skies = factor(skies, levels = c("Clear", "Cloudy")),
         day_night = factor(day_night, levels = c("Night", "Day")),
         cap = ifelse(cap=="YES", 1, 0),
         shirt = ifelse(shirt=="YES", 1, 0),
         fireworks = ifelse(fireworks=="YES", 1, 0),
         bobblehead = ifelse(bobblehead=="YES", 1, 0))

events %>% 
  head() %>%
  pander(caption="Sample Data")
```
## Relation of Variables to Attendance
### Month
```{r collapse=TRUE}

g1 <- ggplot(events, aes(x = month, y = attend, fill = month)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Month")

g1b <- ggplot(events, aes(x = month, y = attend, fill = month, color = bobblehead)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Month")

grid.arrange(g1, g1b, ncol = 2)
```

### Day of the Week
```{r collapse=TRUE}


g2 <- ggplot(events, aes(x = day_of_week, y = attend, fill = day_of_week)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Day of week")

grid.arrange(g2, ncol = 1)
```

### Opponent
```{r collapse=TRUE}

g30 <- ggplot(events, aes(x = opponent, y = attend, fill = opponent)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Opponent")

g30b <- ggplot(events, aes(x = opponent, y = attend, fill = opponent, color = bobblehead)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Opponent")

grid.arrange(g30, g30b, ncol = 2)
```

### Temperature
```{r collapse=TRUE}

g3 <- ggplot(events, aes(x = temp, y = attend, fill = temp)) +
   geom_point() +
   geom_smooth(se=FALSE, method="loess")
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Temperature")

g3b <- ggplot(events, aes(x = temp, y = attend, fill = temp, color = bobblehead)) +
   geom_point() +
   geom_smooth(se=FALSE, method="loess")
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Temperature")

grid.arrange(g3, g3b, ncol = 2)
```

### Skies
```{r collapse=TRUE}

g4 <- ggplot(events, aes(x = skies, y = attend, fill = skies)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Skies")

g4b <- ggplot(events, aes(x = skies, y = attend, fill = skies, color = bobblehead)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Skies")

grid.arrange(g4, g4b, ncol = 2)
```

### Day or Night
```{r collapse=TRUE}

g5 <- ggplot(events, aes(x = day_night, y = attend, fill = day_night)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Day or Night")

g5b <- ggplot(events, aes(x = day_night, y = attend, fill = day_night, color = bobblehead)) +
   geom_boxplot() +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Day or Night")

grid.arrange(g5, g5b, ncol = 2)
```

### Caps
```{r collapse=TRUE}

g6 <- ggplot(events, aes(x = cap, y = attend, fill = cap)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Caps")

g6b <- ggplot(events, aes(x = cap, y = attend, fill = cap, color = bobblehead)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Caps")

grid.arrange(g6, g6b, ncol = 2)
```

### Shirts
```{r collapse=TRUE}

g7 <- ggplot(events, aes(x = shirt, y = attend, fill = shirt)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Shirts")

g7b <- ggplot(events, aes(x = shirt, y = attend, fill = shirt, color = bobblehead)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Shirts")

grid.arrange(g7, g7b, ncol = 2)
```

### Fireworks
```{r collapse=TRUE}

g8 <- ggplot(events, aes(x = fireworks, y = attend, fill = fireworks)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Fireworks")

g8b <- ggplot(events, aes(x = fireworks, y = attend, fill = fireworks, color = bobblehead)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Fireworks")

grid.arrange(g8, g8b, ncol = 2)
```


### Bobblehead
```{r collapse=TRUE}

g8 <- ggplot(events, aes(x = bobblehead, y = attend, fill = bobblehead)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance - Bobblehead")

g8b <- ggplot(events, aes(x = bobblehead, y = attend, fill = bobblehead, color = bobblehead)) +
   geom_point(position="jitter", alpha=0.6) +
   theme(axis.text.x=element_blank(),
   axis.ticks.x=element_blank()) +
   ggtitle("Attendance ( Bobblehead) - Bobblehead")

grid.arrange(g8, g8b, ncol = 2)
```


## Linear Regression Model
```{r collapse=TRUE}
res <- lm(attend ~ month + day_of_week + bobblehead, events)
contrasts(events$month)
contrasts(events$day)
contrasts(events$attend)
contrasts(events$day_of_week)
contrasts(events$opponent)
contrasts(events$temp)
contrasts(events$skies)
contrasts(events$day_night)
contrasts(events$cap)
contrasts(events$shirt)
contrasts(events$fireworks)
contrasts(events$bobblehead)
```
